# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://github.com/fgrehm/vagrant-cachier#quick-start
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  vmbox = "CentOS-6.5-x86_64-v20140311.box"
  vmbox_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140311.box"

  # Kehitystyön tietokantapalvelin
  config.vm.define "aipal-db" do |db|
    db.vm.box = vmbox
    db.vm.box_url = vmbox_url

    db.vm.synced_folder "../env", "/env"
    if File.directory?("../../aipal-konversio")
      db.vm.synced_folder "../../aipal-konversio", "/dumps"
    end
    db.vm.provision "shell", inline: "cd /env && ./db-server.sh local 192.168.50.62"

    # local port 3456 -> vm port 5432
    db.vm.network "forwarded_port", host: 3456, guest: 5432
    db.vm.network "private_network", ip: "192.168.50.61"
  end

  # Kehitystyön sovelluspalvelin
  config.vm.define "aipal-app" do |app|
    app.vm.box = vmbox
    app.vm.box_url = vmbox_url

    app.vm.synced_folder "../env", "/env"
    app.vm.provision "shell", inline: "cd /env && ./app-server.sh local local/ssh/dev_id_rsa.pub"

    app.vm.network "private_network", ip: "192.168.50.62"
  end
end
